#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""板塊分類映射（伺服器端單一真相源，取代前端寫死）。
未列入者歸「其他」；新增幣只要補這張表即可，不需動前端。"""

_MAP = {}

def _reg(sector, syms):
    for s in syms.split():
        _MAP[s.upper()] = sector

_reg("L1", "BTC ETH SOL BNB XRP ADA AVAX SUI APT SEI TON NEAR TRX DOT ATOM ALGO HBAR TIA INJ LTC BCH KAS EGLD FLOW ICP ROSE KAVA CFX MINA XTZ ZIL ONE QTUM WAVES NEO IOTA CELO XLM VET")
_reg("L2", "ARB OP MATIC POL STRK MANTA ZK BLAST METIS IMX MODE TAIKO SCROLL LRC BOBA SKL")
_reg("Meme", "DOGE SHIB PEPE WIF BONK FLOKI BRETT POPCAT MEW NEIRO TURBO BOME MOG PNUT PEOPLE DEGEN MEME BABYDOGE GOAT ACT CHILLGUY MOODENG SPX WOJAK LADYS AIDOGE")
_reg("DeFi", "UNI AAVE MKR LDO CRV COMP SUSHI CAKE PENDLE ENA JUP RAY DYDX GMX SNX RUNE 1INCH BAL YFI SPELL FXS ZRX OSMO JOE VELO AERO MORPHO ETHFI EIGEN")
_reg("AI", "FET RENDER RNDR TAO WLD ARKM AI16Z VIRTUAL NMR GRASS IO AIOZ AGIX OCEAN PHB CGPT TURBO ZEREBRO GRIFFAIN AIXBT")
_reg("DePIN", "RENDER RNDR IO AKT HNT MOBILE IOT DIMO HONEY PRIME ATH PEAQ")
_reg("GameFi", "AXS SAND MANA GALA APE PIXEL BEAM IMX GMT MAGIC RONIN PRIME BIGTIME SUPER YGG ILV WAXP GHST")
_reg("RWA", "ONDO POLYX OM MKR PENDLE CFG TRU CHEX RIO")
_reg("Oracle", "LINK PYTH BAND TRB API3 FLUX")
_reg("Payments", "XRP XLM LTC BCH DASH NANO")
_reg("Privacy", "XMR ZEC DASH SCRT ROSE")
_reg("Storage", "FIL AR STORJ AR BTT SC")
_reg("Exchange", "BNB OKB BGB GT KCS CRO HT MX WOO")
_reg("Liquid-Staking", "LDO RPL FXS ETHFI EIGEN SWELL PUFFER")


def sector_of(sym):
    return _MAP.get((sym or "").upper(), "其他")
